# Generated by Django 5.2.14 on 2026-05-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_course_is_active_course_level'),
        ('academy', '0002_student_profile_picture'),
    ]

    operations = [
    ]
